version: "3.8"

services:

  configserver:
    image: dakarakoso/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - dakarakoso
      
  accounts:
    image: dakarakoso/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - dakarakoso
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  
  loans:
    image: dakarakoso/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - dakarakoso
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
  cards:
    image: dakarakoso/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - dakarakoso
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
 
  gatewayserver:
    image: dakarakoso/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - dakarakoso
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      
      
networks:
  dakarakoso: